<?php

namespace common\components\PhotoManager;

use common\helpers\pelexif\Gps;
use Imagine\Gd\Imagine;
use Imagine\Image\Box;
use Imagine\Image\ImageInterface;
use Yii;
use yii\base\Event;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Exception;
use yii\db\Expression;
use yii\helpers\ArrayHelper;


/**
 * This is the model class for table "photo".
 *
 * @property string $id
 * @property integer $category
 * @property integer $rank
 * @property string $building_id
 * @property string $inventory_id
 * @property string $location_id
 * @property string $title
 * @property string $description
 * @property string $original
 * @property string $medium
 * @property string $thumb
 * @property string $filename
 * @property string $taken_time
 * @property boolean $verified
 * @property string $created_time
 * @property string $updated_time
 *
 * @property Building $building
 * @property Location $location
 */
class Photo extends \yii\db\ActiveRecord
{
    /**
     * @var mixed image the attribute for rendering the file input
     * widget for upload on the form
     */
    public $image;
    public $uploadPath, $uploadUrl;

    const IMAGE_VERSION_ORIGINAL = 'original';
    const IMAGE_VERSION_MEDIUM = 'medium';
    const IMAGE_VERSION_THUMB = 'thumb';

    /**
     * @var bool flag that indicates whether to process for new rank in afterSave
     */
    protected $_processRank = false;



    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->uploadPath = Yii::$app->params['uploadPath'] = Yii::getAlias('`@uploadsPath/');
        $this->uploadUrl = Yii::$app->params['uploadUrl'] = Yii::getAlias('@uploadsUrl/');

    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'photo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category', 'rank', 'building_id', 'location_id'], 'integer'],
            [['inventory_id', 'description', 'original', 'medium', 'thumb', 'filename'], 'string'],
            [['taken_time','created_at', 'updated_at'], 'safe'],
            [['verified'], 'boolean'],
            [['title'], 'string', 'max' => 255],
            [['image'], 'file', 'extensions' => ['jpg', 'gif', 'png'], 'maxSize' => 1024 * 1024 * 2],/* @see: upload_max_filesize in php.ini where 2M = 1024 * 1024 * 2 */
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'category' => Yii::t('app', 'Category'),
            'rank' => Yii::t('app', 'Rank'),
            'building_id' => Yii::t('app', 'Building ID'),
            'inventory_id' => Yii::t('app', 'Inventory ID'),
            'location_id' => Yii::t('app', 'Location ID'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
            'original' => Yii::t('app', 'Original'),
            'medium' => Yii::t('app', 'Medium'),
            'thumb' => Yii::t('app', 'Thumb'),
            'filename' => Yii::t('app', 'Original Filename'),
            'taken_time' => Yii::t('app', 'Taken Time'),
            'verified' => Yii::t('app', 'Verified'),
            'created_at' => Yii::t('app', 'Created Time'),
            'updated_at' => Yii::t('app', 'Updated Time'),
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBuilding()
    {
        return $this->hasOne(Building::className(), ['id' => 'building_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocation()
    {
        return $this->hasOne(Location::className(), ['id' => 'location_id']);
    }

    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
                [
                    'class' => 'common\behaviors\ar\RelatedBehavior',
                ],
                [
                    'class' => 'common\behaviors\ar\RelationBehavior',

                ],
                [// Auto populates Timestamp for created and update events
                    'class' => TimestampBehavior::className(),
                    'createdAtAttribute' => 'created_at',
                    'updatedAtAttribute' => 'updated_at',
                    'value' => new Expression("Now() AT TIME ZONE 'UTC'"),
                ],
            ]
        ); // TODO: Change the autogenerated stub
    }



    //{{{ functions for $image
    public function getFolderName(){
        return implode(
            DIRECTORY_SEPARATOR,
            [
                $this->id
            ]
        );
    }

    /**
     * fetch stored image file name with complete path
     * @return string
     */
    public function getOriginalImageFile()
    {
        return isset($this->original) ? Yii::$app->params['uploadPath'] . $this->original : null;
    }

    /**
     * fetch stored image url
     * @return string
     */
    public function getOriginalImageUrl()
    {
        return Yii::$app->params['uploadUrl'] . $this->original;
    }

    /**
     * fetch stored image file name with complete path
     * @return string
     */
    public function getMediumImageFile()
    {
        return isset($this->medium) ? Yii::$app->params['uploadPath'] . $this->medium : null;
    }

    /**
     * fetch stored image url
     * @return string
     */
    public function getMediumImageUrl()
    {
        return Yii::$app->params['uploadUrl'] . $this->medium;
    }

    /**
     * fetch stored image file name with complete path
     * @return string
     */
    public function getThumbImageFile()
    {
        return isset($this->thumb) ? Yii::$app->params['uploadPath'] . $this->thumb : null;
    }

    /**
     * fetch stored image url
     * @return string
     */
    public function getThumbImageUrl()
    {
        return Yii::$app->params['uploadUrl'] . $this->thumb;
    }

    /**
     * Process deletion of image
     *
     * @return boolean the status of deletion
     */
    public function deleteImage()
    {
        // remove files
        if (is_file($this->getOriginalImageFile()))
            @unlink($this->getOriginalImageFile());
        if (is_file($this->getMediumImageFile()))
            @unlink($this->getMediumImageFile());
        if (is_file($this->getThumbImageFile()))
            @unlink($this->getThumbImageFile());
        // Modify attributes then save
        $this->original = null;
        $this->medium = null;
        $this->thumb = null;


        return true;
    }

    /**
     * @param $uploadedImage \yii\web\UploadedFile
     * @return bool
     */
    public function saveUploadedImage($uploadedImage){
       return $this->saveImage($uploadedImage->tempName,$uploadedImage->extension);
    }

    /**
     * @param $filePath string full file name
     * @return bool
     */
    public function saveImage($filePath,$extension)
    {
        // Get sizes
        list($width, $height) = getimagesize($filePath);

        //using GD library with imagine
        $imagine = new Imagine();
        $imagineImage = $imagine->open($filePath);

        $upload_dir = Yii::getAlias('@uploads/');

        // Set Model Properties
        $this->original = implode('_', [$this->id, Yii::$app->security->generateRandomString(5)]) . '.' . $extension;
        $this->medium = implode('_', [$this->id, Yii::$app->security->generateRandomString(5), 'm']) . '.' . $extension;
        $this->thumb = implode('_', [$this->id, Yii::$app->security->generateRandomString(5), 't']) . '.' . $extension;

        // Now save model and save photos then return true
        if ($this->save()) {
            // filename with path
            $originalFile = $upload_dir . $this->original;
            $mediumFile = $upload_dir . $this->medium;
            $thumbFile = $upload_dir . $this->thumb;

            //original
            $imagineImage->save($originalFile);
            Gps::addGpsInfo($originalFile, $originalFile, $this->description, null, null, 27, 56, 0, null);

            // Medium size
            $medium = $imagineImage->save($mediumFile);
            Gps::addGpsInfo($mediumFile, $mediumFile, $this->description, null, null, 27, 56, 0, null);
            if ($height > 300 || $width > 400) {
                $medium->resize(new Box(400, 300), ImageInterface::FILTER_UNDEFINED)->save($mediumFile);
            }


            // Thumbnail
            $thumb = $imagineImage->save($thumbFile);
            Gps::addGpsInfo($thumbFile, $thumbFile, $this->description, null, null, 27, 56, 0, null);
            if ($height > 59) {
                switch ($height > $width) {
                    case true:
                        $mode = ImageInterface::THUMBNAIL_INSET;
                        break;
                    case false:
                        $mode = ImageInterface::THUMBNAIL_OUTBOUND;
                        break;
                    default:
                        break;
                }
                $thumb->thumbnail(new Box(89, 59), $mode)->save($thumbFile);
            }
            return true;
        }
    }

    /**
     * @param $uploadedImage \yii\web\UploadedFile
     * @return bool
     */
    public function replaceUploadedImage($uploadedImage){
        return $this->replaceImage($uploadedImage->tempName,$uploadedImage->extension);
    }

    /**
     * @param $filePath string
     * @param $extension string
     * @return bool
     */
    public function replaceImage($filePath,$extension)
    {
        $this->deleteImage();
        $this->saveImage($filePath,$extension);
    }
    //Static Functions
    /**
     * fetch stored image file name with complete path
     * @param string $version
     * @return null|string
     * @throws Exception
     */
    public static function getImagePath($id, $version = self::IMAGE_VERSION_ORIGINAL)
    {
        if (!isset($id)) {
            throw new \yii\base\Exception('Id must be specified');
        }
        $model = self::findOne($id);
        switch ($version) {
            case self::IMAGE_VERSION_ORIGINAL:
                return $model->getOriginalImageFile();
                break;
            case self::IMAGE_VERSION_MEDIUM:
                return $model->getMediumImageFile();
                break;
            case self::IMAGE_VERSION_THUMB:
                return $model->getThumbImageFile();
                break;
            default:
                throw new Exception('Could not find the specified image version <' . $version . '> Following versions are available:<br/><ul><li>IMAGE_VERSION_ORIGINAL="original"</li><li>IMAGE_VERSION_MEDIUM="medium"</li><li>IMAGE_VERSION_THUMB="thumb"</li></ul>');
        }
    }

    public static function getImageUrl($id, $version = self::IMAGE_VERSION_ORIGINAL)
    {
        if (!isset($id)) {
            throw new \yii\base\Exception('Id must be specified');
        }
        $model = self::findModel($id);
        switch ($version) {
            case self::IMAGE_VERSION_ORIGINAL:
                return $model->getOriginalImageUrl();
                break;
            case self::IMAGE_VERSION_MEDIUM:
                return $model->getMediumImageUrl();
                break;
            case self::IMAGE_VERSION_THUMB:
                return $model->getThumbImageUrl();
                break;
            default:
                throw new Exception('Could not find the specified image version <' . $version . '> Following versions are available:<br/><ul><li>IMAGE_VERSION_ORIGINAL="original"</li><li>IMAGE_VERSION_MEDIUM="medium"</li><li>IMAGE_VERSION_THUMB="thumb"</li></ul>');
        }
    }

    public function getNewRank()
    {
        return $this->building->getPhotos()->count() + 1;
    }

    public function setRank($rank)
    {
        if (!$rank) {
            throw new \yii\base\Exception('Rank not Specified');
        }
        $this->rank = $rank;
    }
    //}}}

    /**
     * Finds the Photo model based on its primary key value.
     * If the model is not found, a db exception will be thrown.
     * @param $id
     * @return null|static
     * @throws Exception
     */
    public static function findModel($id)
    {
        if (($model = self::findOne($id)) !== null) {
            return $model;
        } else {
            throw new Exception('The requested model was not found');
        }
    }

    //{{{Event Based functions
    /**
     * @param bool $insert
     * @return bool
     * @throws \yii\base\Exception
     */
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->_processRank = true;
            }
            return true;
        }
        return false;
    }

    /**
     * @return bool
     */
    public function beforeDelete()
    {
        if (parent::beforeDelete()) {
            // assign id to cache variable if we need to use it during afterSave event later on.. for example cleaning up related models
            $this->idCache = $this->id;
            $this->deleteImage();
            return true;
        }
        return false;
    }
    //}}}./Event Based functions
}
